[package]
name = "contribcard"
description = "Contribcard CLI tool"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.76"
repository = "https://github.com/cncf/contribcard"
readme = "README.md"
authors = ["Sergio Castaño Arteaga", "Cintia Sanchez Garcia"]

[dependencies]
anyhow = "1.0.80"
askama = { version = "0.12.1", features = ["serde-json"] }
aws-config = "1.1.6"
aws-sdk-s3 = "1.16.0"
axum = "0.7.4"
chrono = "0.4.34"
clap = { version = "4.5.1", features = ["derive"] }
deadpool = "0.10.0"
dirs = "5.0.1"
duckdb = { version = "0.10.0", features = ["json"] }
futures = "0.3.30"
mime_guess = "2.0.4"
parse_link_header = "0.3.3"
reqwest = { version = "0.11.24", features = ["json"] }
rust-embed = "8.2.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_yaml = "0.9.32"
tempfile = "3.10.0"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "signal"] }
tower = "0.4.13"
tower-http = { version = "0.5.1", features = ["fs", "set-header"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
walkdir = "2.4.0"

[build-dependencies]
anyhow = "1.0.80"
which = "6.0.0"
